version: '3.9'

services:
  ai-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data_ml:/app/data_ml
      - ./logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=deploy.settings
      - PORT=8000
    command: ["uvicorn", "deploy.asgi:application", "--host", "0.0.0.0", "--port", "${PORT}"]
    restart: unless-stopped

volumes:
  data_ml:
  logs: